### ISSUE TITLE
How to add the gif to the specified position and size?

### ISSUE THREAD

**Issue by xeoshow** [pixijs/gif#21]
Hello,

I am trying below code, and just would like to add the image.gif to the specified position (x, y) with the specified size (width, height) or specified scale, How should I do? Is the image variable a texture or sprite? 

Thanks v much.

```
import '@pixi/gif';
import { Assets } from 'pixi.js';

const app = new Application();
const image = await Assets.load('image.gif');
app.stage.addChild(image);
```

**Comment by bigtimebuddy** [comment]
The image is a Sprite. So you can set position and scale like you would with a Sprite.

**Comment by gubeils** [comment]
Bug Report: Unable to Load GIF using @pixi/gif with PIXI.js v7.x
Description
Hello,
I encountered a similar issue when trying to load a GIF file using @pixi/gif with PIXI.js version 7.x. The function I am using to load the GIF returns null.
Code Example
Here is the function I am using to load the GIF:
```
import '@pixi/gif';
import { Assets } from 'pixi.js';

async function loadGif() {
  const url = '../../public/assets/year.gif';

  const image = await Assets.load(url);
  console.log('loadGif.image', image);
  app.value.stage.addChild(image);
}

```
The console.log('loadGif.image', image) statement prints null.

Steps to Reproduce
Install @pixi/gif version 2.1.1 and PIXI.js version 7.x.
Create the above function to load a GIF file.
Observe the console output after calling the loadGif function. The image is null instead of an expected PIXI.Texture or PIXI.Sprite.

Expected Behavior
The Assets.load function should load the GIF and return a valid PIXI.Texture or PIXI.Sprite, which can be added to the app.value.stage.

Actual Behavior
The Assets.load function returns null, making it impossible to add the GIF sprite to the stage.
Additional Information

- PIXI.js version: 7.x
- @pixi/gif version: 2.1.1
- Environment: Working on a Vue 3 application, with the following setup in the onMounted lifecycle hook.

Questions
Is there a specific method I need to use to correctly load a GIF file with @pixi/gif?
1.Are there additional configurations or imports required that I might be missing?
2.Any assistance or guidance you can provide on this issue would be greatly appreciated!
Thank you!

**Comment by gubeils** [comment]
I have created a new issue, the link is:
https://github.com/pixijs/gif/issues/22
